create extension if not exists postgis;
create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'product_type') then
    create type product_type as enum ('goods', 'service');
  end if;

  if not exists (select 1 from pg_type where typname = 'price_unit') then
    create type price_unit as enum ('kg', 'piece', 'bunch', 'minute', 'ride');
  end if;

  if not exists (select 1 from pg_type where typname = 'report_source') then
    create type report_source as enum ('manual', 'scan', 'community_seed');
  end if;
end $$;

create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  external_user_id text not null unique,
  nickname text,
  created_at timestamptz not null default now()
);

create table if not exists public.regions (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name_en text not null,
  name_ko text not null,
  country_code text not null default 'EG',
  center geography(point, 4326),
  created_at timestamptz not null default now()
);

create table if not exists public.markets (
  id uuid primary key default gen_random_uuid(),
  region_id uuid not null references public.regions(id) on delete cascade,
  name text not null,
  description text,
  location geography(point, 4326),
  created_at timestamptz not null default now()
);

create index if not exists markets_region_id_idx on public.markets(region_id);
create index if not exists markets_location_idx on public.markets using gist(location);

create table if not exists public.products (
  id text primary key,
  name_en text not null,
  name_ko text not null,
  name_ar text,
  product_type product_type not null default 'goods',
  default_unit price_unit not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.price_reports (
  id uuid primary key default gen_random_uuid(),
  product_id text not null references public.products(id),
  region_id uuid not null references public.regions(id),
  market_id uuid references public.markets(id),
  app_user_id uuid references public.app_users(id),
  source report_source not null default 'manual',
  offered_price numeric(10, 2) not null check (offered_price > 0),
  unit price_unit not null,
  quantity_value numeric(10, 2) not null default 1 check (quantity_value > 0),
  ride_minutes integer check (ride_minutes is null or ride_minutes > 0),
  detected_price numeric(10, 2),
  confidence numeric(5, 4),
  note text,
  lat double precision,
  lon double precision,
  created_at timestamptz not null default now(),
  constraint price_reports_service_minutes_chk check (
    unit <> 'minute' or ride_minutes is not null
  )
);

create index if not exists price_reports_product_region_created_idx
  on public.price_reports(product_id, region_id, created_at desc);
create index if not exists price_reports_market_id_idx
  on public.price_reports(market_id);
create index if not exists price_reports_app_user_id_idx
  on public.price_reports(app_user_id);

create table if not exists public.phrases (
  id bigint generated by default as identity primary key,
  category text not null,
  text_ko text not null,
  text_ar text not null,
  romanized text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create or replace view public.community_feed_v as
select
  pr.id,
  pr.created_at,
  p.id as product_id,
  p.name_ko as product_name,
  p.name_ar as product_name_ar,
  r.name_ko as region_name,
  m.name as market_name,
  pr.offered_price,
  pr.unit,
  pr.quantity_value,
  pr.ride_minutes,
  avg(pr.offered_price) over (partition by pr.product_id, pr.region_id) as avg_price
from public.price_reports pr
join public.products p on p.id = pr.product_id
join public.regions r on r.id = pr.region_id
left join public.markets m on m.id = pr.market_id;

create or replace function public.get_price_stats(
  p_product_id text,
  p_region_id uuid
)
returns table (
  product_id text,
  avg_price numeric,
  mode_price numeric,
  max_price numeric,
  min_price numeric,
  std_dev numeric,
  sample_count bigint
)
language sql
stable
as $$
  with base as (
    select offered_price
    from public.price_reports
    where product_id = p_product_id
      and region_id = p_region_id
  ),
  mode_cte as (
    select offered_price
    from base
    group by offered_price
    order by count(*) desc, offered_price asc
    limit 1
  )
  select
    p_product_id as product_id,
    round(avg(offered_price)::numeric, 2) as avg_price,
    (select offered_price from mode_cte) as mode_price,
    round(max(offered_price)::numeric, 2) as max_price,
    round(min(offered_price)::numeric, 2) as min_price,
    round(coalesce(stddev_pop(offered_price), 0)::numeric, 2) as std_dev,
    count(*) as sample_count
  from base;
$$;

create or replace function public.get_nearby_markets(
  p_lat double precision,
  p_lon double precision,
  p_radius_m integer default 3000
)
returns table (
  market_id uuid,
  region_id uuid,
  market_name text,
  description text,
  lat double precision,
  lon double precision,
  distance_m double precision
)
language sql
stable
as $$
  select
    m.id as market_id,
    m.region_id,
    m.name as market_name,
    m.description,
    st_y(m.location::geometry) as lat,
    st_x(m.location::geometry) as lon,
    st_distance(
      m.location,
      st_setsrid(st_makepoint(p_lon, p_lat), 4326)::geography
    ) as distance_m
  from public.markets m
  where m.location is not null
    and st_dwithin(
      m.location,
      st_setsrid(st_makepoint(p_lon, p_lat), 4326)::geography,
      p_radius_m
    )
  order by distance_m asc;
$$;

insert into public.products (id, name_en, name_ko, name_ar, product_type, default_unit)
values
  ('p001', 'Grapes', '포도', 'عنب', 'goods', 'kg'),
  ('camel_ride', 'Camel Ride', '낙타 이용', 'ركوب الجمل', 'service', 'minute')
on conflict (id) do nothing;

insert into public.regions (code, name_en, name_ko)
values
  ('cairo-khan', 'Khan el-Khalili', '카이로 칸엘칼릴리'),
  ('giza-pyramids', 'Giza Pyramids Area', '기자 피라미드 인근')
on conflict (code) do nothing;
